# Generated by Django 2.2.4 on 2021-05-11 11:00

from django.db import migrations
import phonenumbers


def normalize_phone_number(apps, shema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(parsed_phonenumber):
            flat.owner_pure_phone = phonenumbers.format_number(parsed_phonenumber, phonenumbers.PhoneNumberFormat.E164)
            flat.save()
        else:
            flat.owner_pure_phone = 'Неверный номер владельца'
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
    	migrations.RunPython(normalize_phone_number)
    ]
